### ISSUE TITLE
Input string was not in a correct format

### ISSUE THREAD

**Issue by filippobottega** [afit/wlan10#54]
---------------------------
Unexpected error
---------------------------
The application encountered an unexpected error while parsing a network. You can continue using the app, but some profiles may be missing. Please report this error to the developer ("https://github.com/afit/wlan10/Issues")

Error details:

Input string was not in a correct format.

   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)

   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)

   at System.Int32.Parse(String s)

   at Net.Bertware.Wlan10.Model.WlanNetwork..ctor(String name)

Tabella codici attiva: 65001

Profilo realme GT Master Edition sull'interfaccia Wi-Fi: 

======================================================================= 

Applicato/a: Tutti i profili utente    

Informazioni profilo 

------------------- 

    Versione               : 1

    Tipo                   : LAN wireless

    Nome                   : realme GT Master Edition

    Opzioni di controllo   : 

        Modalità connessione     : Connetti automaticamente

        Broadcast rete          : Connetti solo in presenza di

                                  broadcast della rete

        Passaggio automatico     : Non passare ad altre reti

        Assegnazione casuale indirizzi MAC  : disabilitata

Impostazioni connettività 

--------------------- 

    Numero di SSID         : 1

    Nome SSID                    : "realme GT Master Edition"

    Tipo rete              : Infrastruttura

    Tipo frequenza radio              : [ Qualsiasi tipo frequenza radio ]

    Estensione fornitore   : non presente

Impostazioni sicurezza 

----------------- 

    Autenticazione         : WPA2-Personal

    Crittografia               : CCMP

    Autenticazione         : WPA2-Personal

    Crittografia               : GCMP

    Chiave di sicurezza      : Presente

Impostazioni costo 

------------- 

    Costo                   : Senza restrizioni

    Traffico eccessivo              : No

    Limite dati quasi raggiunto : No

    Limite dati superato        : No

    Roaming                : No

    Origine costo            : Predefinito

---------------------------
OK   
---------------------------

**Comment by afit** [comment]
Thank you, I will take a look!

**Comment by afit** [comment]
Does [Wifinian](https://github.com/emoacht/Wifinian)'s approach work for you?
